# fly.toml app configuration file generated for practice-microposts on 2023-12-06T01:58:54Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "practice-microposts"
primary_region = "nrt"
console_command = "php /var/www/html/artisan tinker"

[build]
  [build.args]
    NODE_VERSION = "18"
    PHP_VERSION = "8.1"

[env]
  APP_URL = "https://practice-microposts.fly.dev/"
  APP_NAME = "microposts"
  APP_DEBUG = true
  DB_CONNECTION = "pgsql"
  DB_HOST = "db.ewribebixreocpjqqnyx.supabase.co"
  DB_PORT = "5432"
  DB_DATABASE = "postgres"
  DB_USERNAME = "postgres"
  APP_ENV = "production"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
  SESSION_DRIVER = "cookie"
  SESSION_SECURE_COOKIE = "true"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
